# Generated by Django 3.0.4 on 2020-03-30 13:49

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=25)),
                ('turf_location', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=30)),
                ('tournament_prize', models.IntegerField()),
                ('tournament_poster', cloudinary.models.CloudinaryField(max_length=255, verbose_name='tournament_poster')),
                ('tournament_date', models.DateField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack.Turf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot_one', models.TimeField()),
                ('time_slot_two', models.TimeField()),
                ('time_slot_three', models.TimeField()),
                ('day', models.CharField(choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THUR', 'THURSDAY'), ('FRI', 'FRIDAY')], max_length=4)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack.Turf')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.IntegerField()),
                ('time_booked', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack.Turf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
