# Generated by Django 3.0.4 on 2020-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0002_booking_schedule_tournament_turf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
