# Generated by Django 3.0.4 on 2020-03-31 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0003_auto_20200330_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
