# Generated by Django 3.0.4 on 2020-03-31 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0004_auto_20200331_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_prize',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('players', models.IntegerField()),
                ('payment_method', models.CharField(max_length=20)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullstack.Tournament')),
            ],
        ),
    ]
