# Generated by Django 3.0.4 on 2020-03-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullstack', '0006_auto_20200331_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
